# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_SUPPORTS_64_BIT_APPS := true

# Platform
TARGET_BOARD_PLATFORM := mt6768
TARGET_NO_BOOTLOADER := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_USES_MTK_HARDWARE := true

# Kernel & Boot Image Headers
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 buildvariant=user androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x07c08000
BOARD_SECOND_OFFSET := 0x00e88000
BOARD_TAGS_OFFSET := 0x0bc08000
BOARD_DTB_OFFSET := 0x0bc08000
BOARD_BOOT_HEADER_VERSION := 2

# DTB Configuration
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
TARGET_PREBUILT_KERNEL := device/infinix/X682C/prebuilt/Image.gz-dtb
TARGET_PREBUILT_DTB := device/infinix/X682C/prebuilt/dtb.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)

BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_SECOND_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --os_version 10.0.0
BOARD_MKBOOTIMG_ARGS += --os_patch_level 2022-07


# Compression
OF_USE_LZMA_COMPRESSION := 1
LZMA_RAMDISK_TARGETS := recovery
BOARD_RAMDISK_USE_LZMA := true

# --- Essential OrangeFox Size Reduction (Required for GZIP) ---
#OFOX_DISABLE_EXTRA_FEATURES := true
#FOX_ENABLE_APP_MANAGER := false
#OFOX_REMOVE_AAPT := true
#TW_EXCLUDE_L10N := true

# Display & UI Setup
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1640
TW_THEME := portrait_hdpi
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 200
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_GRALLOC_BUILD_INLINE := true
TW_CUSTOM_BATTERY_PATH := "/sys/class/power_supply/battery"
TARGET_RECOVERY_DEFAULT_TIME_ZONE := "Asia/Calcutta"

# Partitions & Sizes
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432

# Dynamic / Logical Partitions
BOARD_SUPER_PARTITION_SIZE := 5855272960
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_PARTITION_LIST := system vendor product
BOARD_MAIN_SIZE := 5851078656
BOARD_SUPER_PARTITION_BLOCK_DEVICES := super
BOARD_SUPER_DEVICE_SUPER_DEVICE_SIZE := 5855272960
BOARD_SUPER_PARTITION_METADATA_DEVICE := super

# Android Verified Boot (AVB)
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2
BOARD_AVB_RECOVERY_KEY_PATH := build/make/target/product/security/testkey.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# OrangeFox & TWRP Features
OFOX_AB_DEVICE := false
OFOX_BANNED_USB_PATH := /sys/devices/platform/mt_usb
OFOX_FLASHLIGHT_ENABLE := true
OFOX_FLASHLIGHT_PATH := /sys/class/leds/torch
TW_INCLUDE_RESETPROP := true
TW_NO_SECURE_ADBD := true
TW_HAS_MTP := true

# Fastbootd & Logical Management
TW_INCLUDE_LOGICAL := true
TW_INCLUDE_FASTBOOTD := true
TW_FASTBOOT_MODE := true
TW_FLASH_LOGICAL := true
OFOX_ALLOW_LOGICAL_PARTITIONS := true

# Hardware Crypto (Beanpod Keymaster / Gatekeeper)
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := false
TW_INCLUDE_FBE_METADATA_DECRYPT := false
BOARD_USES_METADATA_PARTITION := false
